name: vascomm
version: 1.0.0+1
publish_to: none
description: Skill test project for Mobile Developer - Freelance at Vascomm.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  get: ^4.6.1
  responsive_sizer: ^3.0.5+1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    
  fonts:
  - family: Gilroy
    fonts:
      - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
        weight: 100
      - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf
        weight: 200
      - asset: assets/fonts/gilroy/Gilroy-Light.ttf
        weight: 300
      - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        weight: 400
      - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
        weight: 500
      - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
        weight: 600
      - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        weight: 700
      - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
        weight: 900
  - family: Proxima Nova
    fonts:
      - asset: assets/fonts/proxima_nova/Proxima-Nova-Thin.otf
        weight: 100
      - asset: assets/fonts/proxima_nova/Proxima-Nova-Thin.otf
        weight: 200
      - asset: assets/fonts/proxima_nova/Proxima-Nova-Light.otf
        weight: 300
      - asset: assets/fonts/proxima_nova/Proxima-Nova-Regular.otf
        weight: 400
      - asset: assets/fonts/proxima_nova/Proxima-Nova-Regular.otf
        weight: 500
      - asset: assets/fonts/proxima_nova/Proxima-Nova-Bold.otf
        weight: 600
      - asset: assets/fonts/proxima_nova/Proxima-Nova-Bold.otf
        weight: 700
      - asset: assets/fonts/proxima_nova/Proxima-Nova-ExtraBold.otf
        weight: 800
      - asset: assets/fonts/proxima_nova/Proxima-Nova-Black.otf
        weight: 900
